### ISSUE TITLE
Scoping - Ecore Reference Check

### ISSUE THREAD

**Issue by MartinLoeper** [MartinLoeper/KAMP-DSL#1]
Why is an equals check not working as expected for the following method in KampRuleLanguageScopeProviderDelegate class?
```
	override getScope(EObject context, EReference reference) {
		if (context instanceof KampRule && reference.equals(METACLASS_REFERENCE__METACLASS))
			return IScope.NULLSCOPE
		else if (context instanceof BackwardEReference && reference.class.isAssignableFrom(METACLASS_REFERENCE__METACLASS.class))
			return createFilteredEReferenceScope((context as BackwardEReference)?.metaclass,
				(context as Lookup)?.previousMetaclass)
		else if (context instanceof Lookup && reference.class.isAssignableFrom(METACLASS_REFERENCE__METACLASS.class)) {
			return createEReferenceScope((context as Lookup)?.previousMetaclass)
		}
		
		return super.getScope(context, reference)
	}
```

I am using `reference.class.isAssignableFrom(METACLASS_REFERENCE__METACLASS.class)` instead now.
Is this correct?

**Comment by dwerle** [comment]
If I'm not mistaken, `reference.class` and `METACLASS_REFERENCE__METACLASS.class` should both evaluate to `EReference` in any case, so this check should always return true.

I would think the equals check to be the correct one. In which way does it not work as expected? Another problem could be that Xtext uses a different `context` when not all elements in the rule are correctly specified by the user or if the linking fails.
