### ISSUE TITLE
Misc: Interesting Development Tools

### ISSUE THREAD

**Issue by MartinLoeper** [MartinLoeper/KAMP-DSL#48]
Here is a selection of interesting dev tools which I might check out in the spare time.

**Comment by MartinLoeper** [comment]
https://www.codacy.com/

**Comment by MartinLoeper** [comment]
https://coveralls.io/github/s-a/time-track?branch=master

**Comment by layornos** [comment]
"Spare time"?! What is that? :D

**Comment by MartinLoeper** [comment]
That is something that usually does not exist here at KIT 🙁

**Comment by layornos** [comment]
Whatcha talkin bout, boooi? :D

**Comment by MartinLoeper** [comment]
Tools are not interesting enough to invest time in the near future.
