### ISSUE TITLE
Create base classes for common rule customizations

### ISSUE THREAD

**Issue by MartinLoeper** [MartinLoeper/KAMP-DSL#49]
Create some base classes for the IRule Interface which solve common tasks.
e.g.: TimeMeasurementRule (field of use see: #46)

**Comment by MartinLoeper** [comment]
We could also use DI (e.g. Google Guice) and inject the required functionality via interfaces.

**Comment by layornos** [comment]
I like the idea of using a di framework. +1

**Comment by MartinLoeper** [comment]
I implemented a custom DI framework.

**Comment by MartinLoeper** [comment]
see:
2c9e4d4f05b1488dbb096852580921b771b90250
41c24e76ce01d80abf50041ef458f6314b1112cb
dd009f6da3a31ff4a773977eaeef509ef9c0d89d
